In [178]:
import pandas as pd

In [179]:
pwd

'/home/pavanigangula'

In [180]:
df = pd.read_csv("/home/pavanigangula/Analysis_data_V2.csv")

In [181]:
df.head()

,ActionPoint,A1,A2,A3,A4,A5,A6,A7,A8,A9,...,A161,A162,A163,A164,A165,A166,A167,A168,A169,A170
0,neg,76698,NaN,2.130706e+09,280.0,0.0,0.0,0.0,0.0,0.0,...,1240520.0,493384.0,721044.0,469792.0,339156.0,157956.0,73224.0,0.0,0.0,0.0
1,neg,33058,NaN,0.000000e+00,NaN,0.0,0.0,0.0,0.0,0.0,...,421400.0,178064.0,293306.0,245416.0,133654.0,81140.0,97576.0,1500.0,0.0,0.0
2,neg,41040,NaN,2.280000e+02,100.0,0.0,0.0,0.0,0.0,0.0,...,277378.0,159812.0,423992.0,409564.0,320746.0,158022.0,95128.0,514.0,0.0,0.0
3,neg,12,0.0,7.000000e+01,66.0,0.0,10.0,0.0,0.0,0.0,...,240.0,46.0,58.0,44.0,10.0,0.0,0.0,0.0,4.0,32.0
4,neg,60874,NaN,1.368000e+03,458.0,0.0,0.0,0.0,0.0,0.0,...,622012.0,229790.0,405298.0,347188.0,286954.0,311560.0,433954.0,1218.0,0.0,0.0

In [182]:
df.dtypes

ActionPoint     object
A1               int64
A2             float64
A3             float64
A4             float64
A5             float64
A6             float64
A7             float64
A8             float64
A9             float64
A10            float64
A11            float64
A12            float64
A13            float64
A14            float64
A15            float64
A16            float64
A17            float64
A18            float64
A19            float64
A20            float64
A21            float64
A22            float64
A23            float64
A24            float64
A25            float64
A26            float64
A27            float64
A28            float64
A29            float64
                ...
A141           float64
A142           float64
A143           float64
A144           float64
A145           float64
A146           float64
A147           float64
A148           float64
A149           float64
A150           float64
A151           float64
A152           float64
A153           float64
A154           float64
A155           float64
A156           float64
A157           float64
A158           float64
A159           float64
A160           float64
A161           float64
A162           float64
A163           float64
A164           float64
A165           float64
A166           float64
A167           float64
A168           float64
A169           float64
A170           float64
Length: 171, dtype: object

In [183]:
df.A1 = df.A1.astype(float)

In [184]:
df.dtypes

ActionPoint     object
A1             float64
A2             float64
A3             float64
A4             float64
A5             float64
A6             float64
A7             float64
A8             float64
A9             float64
A10            float64
A11            float64
A12            float64
A13            float64
A14            float64
A15            float64
A16            float64
A17            float64
A18            float64
A19            float64
A20            float64
A21            float64
A22            float64
A23            float64
A24            float64
A25            float64
A26            float64
A27            float64
A28            float64
A29            float64
                ...
A141           float64
A142           float64
A143           float64
A144           float64
A145           float64
A146           float64
A147           float64
A148           float64
A149           float64
A150           float64
A151           float64
A152           float64
A153           float64
A154           float64
A155           float64
A156           float64
A157           float64
A158           float64
A159           float64
A160           float64
A161           float64
A162           float64
A163           float64
A164           float64
A165           float64
A166           float64
A167           float64
A168           float64
A169           float64
A170           float64
Length: 171, dtype: object

In [185]:
df[input_cols] = df[input_cols].fillna(0).astype(np.int64)

In [188]:
input_cols = df.drop(columns='ActionPoint').columns

In [189]:
input_cols

Index(['A1', 'A2', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'A9', 'A10',
       ...
       'A161', 'A162', 'A163', 'A164', 'A165', 'A166', 'A167', 'A168', 'A169',
       'A170'],
      dtype='object', length=170)

In [190]:
from sklearn.preprocessing import StandardScaler
x = df[input_cols].values
y = df['ActionPoint'].values
#x = StandardScaler().fit_transform(x)

In [191]:
x = StandardScaler().fit_transform(x)
x

/opt/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/opt/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)

array([[ 0.12312366, -0.09600634,  2.30933224, ..., -0.17562738,
        -0.02029877, -0.02358854],
       [-0.17952148, -0.09600634, -0.43302611, ..., -0.14371379,
        -0.02029877, -0.02358854],
       [-0.12416599, -0.09600634, -0.43302581, ..., -0.16469166,
        -0.02029877, -0.02358854],
       ...,
       [ 0.65755172, -0.09600634, -0.43302611, ...,  0.11108439,
        -0.02029877, -0.02358854],
       [-0.39503479, -0.09600634,  2.30933224, ..., -0.17562738,
        -0.02029877, -0.02358854],
       [-0.40868295,  1.08801242, -0.43302606, ..., -0.17562738,
        -0.02029877, -0.02358854]])

In [192]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
principalComponents = pca.fit_transform(x)
principalDf = pd.DataFrame(data = principalComponents
             , columns = ['principal component 1', 'principal component 2'])

In [193]:
finalDf = pd.concat([principalDf, df[['ActionPoint']]], axis = 1)
finalDf

       principal component 1  principal component 2 ActionPoint
0                   2.467357              -1.093554         neg
1                  -0.635430              -0.684864         neg
2                  -1.206954              -0.003685         neg
3                  -3.212063               0.317418         neg
4                   0.356036              -0.024626         neg
5                  -0.879061              -0.141193         neg
6                  -3.219847               0.235358         neg
7                   2.270719              -0.849444         neg
8                   2.175768              -1.382096         neg
9                   0.204576               0.707886         pos
10                 -1.182715              -0.236210         neg
11                 -0.658618              -0.677218         neg
12                 -3.072179               0.319371         neg
13                  5.176083              -2.084890         neg
14                 -1.425512              -1.154715         neg
15                 -3.183502               0.236131         neg
16                  6.006262               2.589195         neg
17                 -3.155143               0.312760         neg
18                 -3.235906               0.238509         neg
19                 -3.181010               0.242039         neg
20                 -0.921572               1.248679         neg
21                 -3.244909               0.239663         neg
22                  7.366772              -2.330344         neg
23                 25.336999              -4.606939         pos
24                  0.690583              -0.312674         neg
25                 -1.185506              -0.237570         neg
26                 -2.416739               0.169079         neg
27                 -0.432871               0.039018         neg
28                 -3.152936               0.218452         neg
29                 -2.199414               0.284197         neg
...                      ...                    ...         ...
59722               0.251102              -0.662842         neg
59723              -3.213682               0.243225         neg
59724               3.481008              -0.788050         neg
59725              -3.155290               0.248661         neg
59726               1.258385               0.165839         neg
59727              -3.225149               0.232503         neg
59728              -3.129121               0.236774         neg
59729              -0.828479              -0.118686         neg
59730              -3.194318               0.235031         neg
59731              -3.225560               0.236177         neg
59732              -2.317401              -0.952499         neg
59733              -3.110908               0.344603         neg
59734              -1.341792              -0.160738         neg
59735              -3.161466               0.246346         neg
59736              -1.271088              -0.151665         neg
59737              -3.166139               0.246092         neg
59738              -3.245351               0.233249         neg
59739              -1.934686               0.325612         neg
59740              -0.326384              -0.037991         neg
59741               0.966926              -1.487612         neg
59742               5.151122               6.458697         neg
59743               3.587593               0.356849         neg
59744              -3.222695               0.239996         neg
59745               0.458812              -0.754458         neg
59746               1.652285              -0.348506         neg
59747              -2.386356              -0.923695         neg
59748              -2.965144               0.160653         neg
59749               5.607724              -3.434528         neg
59750              -3.144793               0.248623         neg
59751              -3.222207               0.273791         neg

[59752 rows x 3 columns]

In [194]:
df1 = pd.read_csv("/home/pavanigangula/Scoring_data_V2.csv") 
df1.head()
#df1 = sc.transform(df1)

,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,...,A161,A162,A163,A164,A165,A166,A167,A168,A169,A170
0,29858,NaN,0.000000e+00,NaN,0.0,0.0,0.0,0.0,0.0,0.0,...,237154.0,129448.0,347706.0,556440.0,134946.0,8298.0,134.0,0.0,0.0,0.0
1,12,0.0,4.400000e+01,26.0,0.0,0.0,0.0,0.0,0.0,0.0,...,242.0,32.0,58.0,38.0,14.0,0.0,0.0,0.0,0.0,0.0
2,10,2.0,3.200000e+01,14.0,0.0,0.0,0.0,0.0,0.0,0.0,...,76.0,34.0,58.0,30.0,26.0,44.0,0.0,0.0,0.0,0.0
3,40928,0.0,1.292000e+03,1260.0,0.0,0.0,0.0,0.0,0.0,4050.0,...,549892.0,160796.0,210458.0,132970.0,166826.0,564790.0,152.0,0.0,0.0,0.0
4,80368,NaN,2.130707e+09,1208.0,0.0,0.0,0.0,0.0,0.0,0.0,...,866584.0,395738.0,729136.0,951410.0,303240.0,191938.0,170490.0,6254.0,0.0,0.0

In [195]:
df2 = df1.copy()

In [196]:
df1.dtypes

A1        int64
A2      float64
A3      float64
A4      float64
A5      float64
A6      float64
A7      float64
A8      float64
A9      float64
A10     float64
A11     float64
A12     float64
A13     float64
A14     float64
A15     float64
A16     float64
A17     float64
A18     float64
A19     float64
A20     float64
A21     float64
A22     float64
A23     float64
A24     float64
A25     float64
A26     float64
A27     float64
A28     float64
A29     float64
A30     float64
         ...
A141    float64
A142    float64
A143    float64
A144    float64
A145    float64
A146    float64
A147    float64
A148    float64
A149    float64
A150    float64
A151    float64
A152    float64
A153    float64
A154    float64
A155    float64
A156    float64
A157    float64
A158    float64
A159    float64
A160    float64
A161    float64
A162    float64
A163    float64
A164    float64
A165    float64
A166    float64
A167    float64
A168    float64
A169    float64
A170    float64
Length: 170, dtype: object

In [197]:
df1[input_cols] = df1[input_cols].fillna(0).astype(np.int64)

In [198]:
df1.head()

,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,...,A161,A162,A163,A164,A165,A166,A167,A168,A169,A170
0,29858,0,0,0,0,0,0,0,0,0,...,237154,129448,347706,556440,134946,8298,134,0,0,0
1,12,0,44,26,0,0,0,0,0,0,...,242,32,58,38,14,0,0,0,0,0
2,10,2,32,14,0,0,0,0,0,0,...,76,34,58,30,26,44,0,0,0,0
3,40928,0,1292,1260,0,0,0,0,0,4050,...,549892,160796,210458,132970,166826,564790,152,0,0,0
4,80368,0,2130706530,1208,0,0,0,0,0,0,...,866584,395738,729136,951410,303240,191938,170490,6254,0,0

In [199]:

x1=StandardScaler().fit_transform(df1)
x1

/opt/conda/lib/python3.6/site-packages/sklearn/preprocessing/data.py:645: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/opt/conda/lib/python3.6/site-packages/sklearn/base.py:464: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)

array([[-0.39561798, -0.20989801, -0.39177725, ..., -0.21659813,
         0.        ,  0.        ],
       [-0.49083337, -0.20989801, -0.39177719, ..., -0.21659813,
         0.        ,  0.        ],
       [-0.49083975,  1.5252589 , -0.3917772 , ..., -0.21659813,
         0.        ,  0.        ],
       ...,
       [-0.34721592, -0.20989801, -0.39177624, ..., -0.19024421,
         0.        ,  0.        ],
       [-0.48617565, -0.20989801, -0.39177716, ..., -0.21659813,
         0.        ,  0.        ],
       [-0.49076957, -0.20989801, -0.39177725, ..., -0.21659813,
         0.        ,  0.        ]])

In [200]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
principalComponents = pca.fit_transform(x1)
principalDf1 = pd.DataFrame(data = principalComponents
             , columns = ['principal component 1', 'principal component 2'])

In [201]:
finalDf1 = principalDf1
finalDf1

     principal component 1  principal component 2
0                -2.018022               0.158970
1                -4.191304              -0.023692
2                -4.169367              -0.158107
3                -1.928608              -1.062939
4                -1.389350               0.067493
5                -2.768698               0.411449
6                -2.199289               0.639938
7                -3.102809               0.135546
8                -4.251089              -0.005248
9                -3.327616               0.682256
10               -3.457378               0.587394
11               -4.201798              -0.020750
12                8.780394              -2.679993
13               -4.197968              -0.032344
14               -3.060498               0.164364
15                7.355926              -1.631191
16               -4.101905              -0.116092
17               -2.403759               0.176727
18                9.006348              -3.767762
19                4.404320              -2.075533
20               -1.947527               0.309163
21               -2.856609              -0.060441
22               -1.558743               1.161036
23                4.280577              -1.666347
24               -2.305358               0.165043
25               -4.118423              -0.188624
26               -4.139910               0.003486
27               -4.225354               0.001837
28               -4.233187               0.032288
29               -2.277664               0.868252
..                     ...                    ...
218               8.585353              -8.882165
219              -0.274574               2.307099
220              -1.425123               0.637586
221              -4.093282              -0.080862
222              -2.393589              -0.310278
223              -3.109671               0.050322
224              -2.552528               0.813413
225               6.440223              -1.972568
226              -1.252832               1.445665
227              -2.628810               0.439015
228              -2.890854               0.242074
229              -3.106532               0.243376
230              27.875534              -8.221385
231              12.562230               5.566552
232               2.882096              -0.045069
233              -2.896792               0.270200
234              25.220870              -3.057417
235              -3.315089               0.024820
236              -2.275111               0.247198
237              -4.180769              -0.033086
238               7.593054              -4.751429
239              -4.200915              -0.022351
240              -3.209406               0.545391
241              -2.748876               0.493188
242              -2.007761               0.052745
243              -3.342935               0.059458
244              -3.186285              -0.019402
245              -3.181764               0.130944
246              -4.159958              -0.059355
247              -4.183358              -0.013311

[248 rows x 2 columns]

In [202]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 1000, random_state = 50)

from sklearn.model_selection import train_test_split
#import numpy as np
#labels = np.array(df['ActionPoint'])
#features= df.drop('ActionPoint', axis = 1)
#feature_list = list(features.columns)
#features = np.array(features)
#rf.fit(features,labels)

In [203]:
X = finalDf.iloc[:,0:2]
y = finalDf['ActionPoint']

In [204]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [205]:
#from sklearn.linear_model import LogisticRegression   
  
#classifier = LogisticRegression(random_state = 0) 
rf.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=1000, n_jobs=None,
            oob_score=False, random_state=50, verbose=0, warm_start=False)

In [206]:
#rf.predict(finalDf1)

In [207]:
rf.score(X_test,y_test)

0.9859425989456949

In [208]:
rf.score(X_train,y_train)

1.0

In [209]:
y_scoring = rf.predict(finalDf1)

In [210]:
y_scoring1 = pd.DataFrame(y_scoring,columns=['ActionPoint']).copy()

In [211]:
y_scoring1

    ActionPoint
0           neg
1           neg
2           neg
3           neg
4           neg
5           neg
6           neg
7           neg
8           neg
9           neg
10          neg
11          neg
12          neg
13          neg
14          neg
15          neg
16          neg
17          neg
18          neg
19          neg
20          neg
21          neg
22          neg
23          neg
24          neg
25          neg
26          neg
27          neg
28          neg
29          neg
..          ...
218         neg
219         neg
220         neg
221         neg
222         neg
223         neg
224         neg
225         neg
226         neg
227         neg
228         neg
229         neg
230         pos
231         pos
232         neg
233         neg
234         neg
235         neg
236         neg
237         neg
238         neg
239         neg
240         neg
241         neg
242         neg
243         neg
244         neg
245         neg
246         neg
247         neg

[248 rows x 1 columns]

In [212]:
scoring_final = pd.concat([df2,y_scoring1],axis=1)

In [213]:
scoring_final

,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,...,A162,A163,A164,A165,A166,A167,A168,A169,A170,ActionPoint
0,29858,NaN,0.000000e+00,NaN,0.0,0.0,0.0,0.0,0.0,0.0,...,129448.0,347706.0,556440.0,134946.0,8298.0,134.0,0.0,0.0,0.0,neg
1,12,0.0,4.400000e+01,26.0,0.0,0.0,0.0,0.0,0.0,0.0,...,32.0,58.0,38.0,14.0,0.0,0.0,0.0,0.0,0.0,neg
2,10,2.0,3.200000e+01,14.0,0.0,0.0,0.0,0.0,0.0,0.0,...,34.0,58.0,30.0,26.0,44.0,0.0,0.0,0.0,0.0,neg
3,40928,0.0,1.292000e+03,1260.0,0.0,0.0,0.0,0.0,0.0,4050.0,...,160796.0,210458.0,132970.0,166826.0,564790.0,152.0,0.0,0.0,0.0,neg
4,80368,NaN,2.130707e+09,1208.0,0.0,0.0,0.0,0.0,0.0,0.0,...,395738.0,729136.0,951410.0,303240.0,191938.0,170490.0,6254.0,0.0,0.0,neg
5,53834,NaN,3.640000e+02,348.0,0.0,0.0,0.0,0.0,0.0,0.0,...,188002.0,371962.0,343496.0,273852.0,245276.0,515358.0,23652.0,0.0,0.0,neg
6,78918,NaN,8.800000e+02,746.0,0.0,0.0,0.0,0.0,0.0,0.0,...,402082.0,895906.0,798030.0,536888.0,245922.0,120654.0,218.0,0.0,0.0,neg
7,44446,NaN,2.640000e+02,240.0,0.0,0.0,0.0,0.0,0.0,0.0,...,162002.0,361632.0,309064.0,281072.0,238320.0,320826.0,28.0,0.0,0.0,neg
8,18,0.0,2.130706e+09,18.0,0.0,0.0,0.0,0.0,0.0,0.0,...,16.0,34.0,22.0,86.0,10.0,0.0,0.0,0.0,0.0,neg
9,39052,NaN,2.130706e+09,936.0,0.0,0.0,0.0,0.0,0.0,0.0,...,83192.0,152446.0,172890.0,133922.0,120920.0,520692.0,187390.0,0.0,0.0,neg
10,60798,NaN,2.130706e+09,NaN,0.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,neg
11,1580,NaN,2.880000e+02,260.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2976.0,27786.0,32048.0,908.0,130.0,254.0,46.0,0.0,0.0,neg
12,651942,0.0,1.198000e+03,566.0,0.0,0.0,0.0,568.0,142048.0,2863320.0,...,996020.0,2290202.0,3009840.0,2745146.0,670502.0,20284.0,0.0,0.0,0.0,neg
13,6,0.0,4.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,neg
14,39868,NaN,8.200000e+01,72.0,0.0,0.0,0.0,0.0,0.0,0.0,...,171916.0,473916.0,486990.0,203882.0,103926.0,70546.0,74.0,0.0,0.0,neg
15,541530,NaN,NaN,NaN,NaN,NaN,0.0,9836.0,476728.0,5066604.0,...,1516780.0,3906754.0,7229264.0,8038736.0,872932.0,81848.0,56.0,NaN,NaN,neg
16,1578,NaN,1.660000e+02,154.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3468.0,5962.0,52752.0,640.0,168.0,288.0,32.0,0.0,0.0,neg
17,39550,NaN,3.282000e+03,2316.0,0.0,0.0,0.0,0.0,0.0,0.0,...,191080.0,323638.0,260080.0,163022.0,93472.0,107416.0,126.0,0.0,0.0,neg
18,614656,0.0,3.600000e+02,NaN,0.0,0.0,0.0,14532.0,630268.0,4753042.0,...,863058.0,1989896.0,2362762.0,3796424.0,6138312.0,230628.0,0.0,0.0,0.0,neg
19,76812,0.0,3.760000e+02,340.0,0.0,0.0,0.0,0.0,5744.0,464102.0,...,60100.0,29754.0,4200.0,4070.0,9236.0,0.0,0.0,0.0,0.0,neg
20,31310,NaN,0.000000e+00,NaN,0.0,0.0,0.0,0.0,0.0,0.0,...,134630.0,253790.0,259758.0,155246.0,120900.0,207170.0,11732.0,0.0,0.0,neg
21,47332,NaN,6.600000e+02,652.0,0.0,0.0,0.0,0.0,0.0,0.0,...,229008.0,594804.0,615400.0,339224.0,62576.0,8690.0,44.0,0.0,0.0,neg
22,104910,NaN,2.240000e+02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,451276.0,897990.0,855508.0,689156.0,382178.0,467906.0,45324.0,0.0,0.0,neg
23,594350,0.0,8.280000e+02,NaN,0.0,0.0,0.0,0.0,106756.0,1578360.0,...,229366.0,506728.0,765148.0,1492612.0,3097968.0,15862.0,0.0,0.0,0.0,neg
24,52482,NaN,2.130706e+09,1008.0,0.0,0.0,0.0,0.0,0.0,0.0,...,297356.0,649944.0,420258.0,245570.0,135162.0,64850.0,528.0,0.0,0.0,neg
25,1966,0.0,2.600000e+01,18.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4938.0,11526.0,15630.0,19284.0,16094.0,590.0,0.0,0.0,0.0,neg
26,742,NaN,1.800000e+01,14.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2190.0,4524.0,4566.0,6104.0,6620.0,6.0,0.0,0.0,0.0,neg
27,2414,NaN,5.200000e+01,52.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5002.0,63340.0,34284.0,1596.0,36.0,0.0,0.0,0.0,0.0,neg
28,1302,NaN,2.130706e+09,30.0,0.0,0.0,0.0,0.0,0.0,0.0,...,22766.0,13630.0,6306.0,202.0,4.0,0.0,0.0,0.0,0.0,neg
29,61844,NaN,7.240000e+02,612.0,0.0,0.0,0.0,0.0,0.0,0.0,...,152324.0,257222.0,169914.0,166276.0,152462.0,833726.0,334370.0,0.0,0.0,neg
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218,65052,NaN,1.235140e+05,194868.0,0.0,0.0,0.0,0.0,0.0,0.0,...,135710.0,6674.0,452.0,178.0,42.0,54.0,0.0,0.0,0.0,neg
219,146432,NaN,2.130706e+09,NaN,0.0,0.0,0.0,0.0,0.0,50032.0,...,598432.0,862602.0,539474.0,93470.0,19310.0,7046.0,0.0,0.0,0.0,neg
220,101202,NaN,2.130706e+09,680.0,0.0,0.0,0.0,0.0,0.0,316.0,...,506772.0,923996.0,741064.0,518778.0,323918.0,597090.0,36396.0,0.0,0.0,neg
221,1886,0.0,1.800000e+01,18.0,0.0,0.0,0.0,0.0,0.0,288.0,...,2792.0,5494.0,9364.0,27194.0,27414.0,320.0,0.0,0.0,0.0,neg
222,10792,NaN,7.840000e+02,608.0,0.0,0.0,0.0,0.0,0.0,0.0,...,49046.0,98602.0,55236.0,15122.0,10052.0,18538.0,856.0,0.0,0.0,neg
223,38374,NaN,2.700000e+02,270.0,0.0,0.0,0.0,0.0,0.0,0.0,...,124888.0,248848.0,209148.0,198426.0,193066.0,357850.0,12640.0,0.0,0.0,neg
224,61478,NaN,1.340000e+02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,410326.0,1130874.0,535990.0,205766.0,39694.0,550.0,0.0,0.0,0.0,neg
225,687826,NaN,NaN,0.0,NaN,NaN,0.0,0.0,30366.0,2365194.0,...,982996.0,1995528.0,2404554.0,2615852.0,18335460.0,235164.0,0.0,NaN,NaN,neg
226,80292,NaN,2.130706e+09,494.0,0.0,0.0,0.0,0.0,0.0,0.0,...,222654.0,347378.0,225724.0,194440.0,165070.0,802280.0,388422.0,0.0,0.0,neg
227,57504,NaN,2.130706e+09,328.0,0.0,0.0,0.0,0.0,0.0,0.0,...,227296.0,504524.0,390602.0,311826.0,225448.0,485686.0,21772.0,0.0,0.0,neg
228,40222,NaN,6.980000e+02,628.0,0.0,0.0,0.0,0.0,0.0,0.0,...,183200.0,344546.0,254068.0,225148.0,158304.0,170384.0,158.0,0.0,0.0,neg
229,28340,NaN,6.400000e+02,620.0,0.0,0.0,0.0,0.0,0.0,0.0,...,119764.0,211126.0,179244.0,187660.0,185008.0,112618.0,1046.0,0.0,0.0,neg
230,1089044,NaN,NaN,1208.0,NaN,NaN,0.0,14940.0,376334.0,8965652.0,...,4057552.0,9160900.0,14983716.0,11027566.0,1004492.0,16734.0,0.0,NaN,NaN,pos
231,213182,NaN,0.000000e+00,NaN,0.0,0.0,0.0,0.0,954.0,140378.0,...,116894.0,38854.0,5482.0,1898.0,1196.0,2032.0,0.0,0.0,0.0,pos
232,202054,NaN,8.500000e+02,NaN,0.0,0.0,0.0,0.0,49346.0,975082.0,...,846746.0,1472574.0,2720482.0,1751640.0,659638.0,4248.0,0.0,0.0,0.0,neg
233,51114,NaN,0.000000e+00,1208.0,0.0,0.0,0.0,0.0,0.0,0.0,...,172138.0,350442.0,283534.0,267852.0,217202.0,513556.0,12508.0,0.0,0.0,neg
234,846482,NaN,NaN,NaN,0.0,0.0,0.0,10626.0,658358.0,7925986.0,...,4869676.0,8270848.0,12414072.0,338062.0,24788.0,4464.0,0.0,NaN,NaN,neg
235,30320,NaN,1.838000e+03,1278.0,0.0,0.0,0.0,0.0,0.0,0.0,...,86110.0,246966.0,274254.0,220696.0,143046.0,192332.0,5316.0,0.0,0.0,neg
236,46020,NaN,4.160000e+02,342.0,0.0,0.0,0.0,0.0,0.0,0.0,...,224076.0,539056.0,350026.0,221916.0,234510.0,97292.0,4270.0,0.0,0.0,neg
237,1222,NaN,5.800000e+01,48.0,0.0,0.0,0.0,0.0,0.0,0.0,...,840.0,2396.0,48314.0,1140.0,46.0,0.0,0.0,0.0,0.0,neg
238,368776,NaN,NaN,NaN,NaN,NaN,0.0,41788.0,614532.0,5577196.0,...,731042.0,1845026.0,8733418.0,2344170.0,670404.0,53518.0,150.0,NaN,NaN,neg
239,14,0.0,0.000000e+00,26.0,0.0,0.0,0.0,0.0,0.0,0.0,...,26.0,38.0,16.0,0.0,0.0,0.0,0.0,0.0,0.0,neg
240,39278,NaN,0.000000e+00,NaN,0.0,0.0,0.0,0.0,0.0,0.0,...,123822.0,251978.0,266626.0,267334.0,231878.0,316222.0,2602.0,0.0,0.0,neg
241,59956,NaN,0.000000e+00,NaN,0.0,0.0,0.0,0.0,0.0,0.0,...,266500.0,1381660.0,764506.0,105002.0,13714.0,3106.0,0.0,0.0,0.0,neg
242,38414,NaN,8.880000e+02,758.0,0.0,0.0,0.0,0.0,0.0,0.0,...,150648.0,269002.0,200140.0,149768.0,117020.0,270838.0,21082.0,0.0,0.0,neg
243,28294,NaN,7.680000e+02,686.0,0.0,0.0,0.0,0.0,0.0,1282.0,...,148204.0,272812.0,259142.0,170112.0,68556.0,85794.0,1306.0,0.0,0.0,neg
244,30922,NaN,1.074000e+03,968.0,0.0,0.0,0.0,0.0,0.0,0.0,...,118704.0,231952.0,239328.0,189040.0,170226.0,173514.0,1580.0,0.0,0.0,neg
245,45030,NaN,7.300000e+02,576.0,0.0,0.0,0.0,0.0,0.0,0.0,...,134232.0,310532.0,419290.0,423234.0,242578.0,188584.0,2190.0,0.0,0.0,neg
246,1472,NaN,6.000000e+01,54.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4700.0,32906.0,24424.0,776.0,14.0,0.0,0.0,0.0,0.0,neg
247,32,0.0,0.000000e+00,NaN,0.0,0.0,0.0,0.0,0.0,0.0,...,98.0,224.0,166.0,36.0,486.0,0.0,0.0,0.0,0.0,neg

In [214]:
#scoring_final.to_csv('/home/pavanigangula/scoring_final.csv',index=False)